name: Run Unit Tests

on: push

jobs:
  cpython_85299:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Reproduce Runtime Error
      run: |
        python3 main.py

